import localFont from "next/font/local";
import type { Metadata } from "next";
import "./globals.css";

const ChillRoundF = localFont({
  src: [
    {
      path: "../../public/ChillRoundFBold.ttf",
      style: "bold",
    },
    {
      path: "../../public/ChillRoundFRegular.ttf",
      style: "regular",
    },
  ],
});

export const metadata: Metadata = {
  title: "头像添加鱼板跨旗工具",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={ChillRoundF.className}>{children}</body>
    </html>
  );
}
